### ISSUE TITLE
Bug: Windows Release fails with /src/main/resources error

### ISSUE THREAD

**Issue by nicklinn** [crocs-muni/JCAppStore#25] opened 2021-07-19 21:02 UTC
The application fails to run, after succesfull build.
<details>
<summary>Error log</summary>

C:\JCAppStore>java -jar JCAppStore-1.3.exe
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2021-07-19 17:01:08,898 main DEBUG null null initializing configuration XmlConfiguration[location=jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml]
2021-07-19 17:01:08,914 main DEBUG Installed 1 script engine
Warning: Nashorn engine is planned to be removed from a future JDK release
2021-07-19 17:01:09,114 main DEBUG Oracle Nashorn version: 11.0.1, language: ECMAScript, threading: Not Thread Safe, compile: true, names: [nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript], factory class: jdk.nashorn.api.scripting.NashornScriptEngineFactory
2021-07-19 17:01:09,114 main DEBUG PluginManager 'Core' found 122 plugins
2021-07-19 17:01:09,114 main DEBUG PluginManager 'Level' found 0 plugins
2021-07-19 17:01:09,130 main DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
2021-07-19 17:01:09,130 main DEBUG PluginManager 'TypeConverter' found 26 plugins
2021-07-19 17:01:09,146 main DEBUG createProperty(name="ouputFolder", value="${main:0}")
2021-07-19 17:01:09,146 main DEBUG Building Plugin[name=property, class=org.apache.logging.log4j.core.config.Property].
2021-07-19 17:01:09,146 main DEBUG createProperty(name="rollingFileName", value="${main:1}")
2021-07-19 17:01:09,146 main DEBUG Building Plugin[name=properties, class=org.apache.logging.log4j.core.config.PropertiesPlugin].
2021-07-19 17:01:09,146 main DEBUG configureSubstitutor(={ouputFolder=${main:0}, rollingFileName=${main:1}}, Configuration(jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml))
2021-07-19 17:01:09,146 main DEBUG PluginManager 'Lookup' found 15 plugins
2021-07-19 17:01:09,146 main DEBUG Building Plugin[name=layout, class=org.apache.logging.log4j.core.layout.PatternLayout].
2021-07-19 17:01:09,161 main DEBUG PatternLayout$Builder(pattern="[%highlight{%-5level}] %d{DEFAULT} %c{1}.%M() - %msg%n", PatternSelector=null, Configuration(jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml), Replace=null, charset="null", alwaysWriteExceptions="null", disableAnsi="null", noConsoleNoAnsi="null", header="null", footer="null")
2021-07-19 17:01:09,161 main DEBUG PluginManager 'Converter' found 44 plugins
2021-07-19 17:01:09,161 main DEBUG Building Plugin[name=appender, class=org.apache.logging.log4j.core.appender.ConsoleAppender].
2021-07-19 17:01:09,177 main DEBUG ConsoleAppender$Builder(target="SYSTEM_OUT", follow="null", direct="null", bufferedIo="null", bufferSize="null", immediateFlush="null", ignoreExceptions="null", PatternLayout([%highlight{%-5level}] %d{DEFAULT} %c{1}.%M() - %msg%n), name="console", Configuration(jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml), Filter=null, ={})
2021-07-19 17:01:09,177 main DEBUG Starting OutputStreamManager SYSTEM_OUT.false.false
2021-07-19 17:01:09,177 main DEBUG Building Plugin[name=layout, class=org.apache.logging.log4j.core.layout.PatternLayout].
2021-07-19 17:01:09,177 main DEBUG PatternLayout$Builder(pattern="[%highlight{%-5level}] %d{DEFAULT} %c{1}.%M() - %msg%n", PatternSelector=null, Configuration(jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml), Replace=null, charset="null", alwaysWriteExceptions="null", disableAnsi="null", noConsoleNoAnsi="null", header="null", footer="null")
2021-07-19 17:01:09,177 main DEBUG Building Plugin[name=OnStartupTriggeringPolicy, class=org.apache.logging.log4j.core.appender.rolling.OnStartupTriggeringPolicy].
2021-07-19 17:01:09,177 main DEBUG createPolicy(minSize="1")
2021-07-19 17:01:09,177 main DEBUG Building Plugin[name=TimeBasedTriggeringPolicy, class=org.apache.logging.log4j.core.appender.rolling.TimeBasedTriggeringPolicy].
2021-07-19 17:01:09,177 main DEBUG TimeBasedTriggeringPolicy$Builder(interval="1", modulate="true", maxRandomDelay="null")
2021-07-19 17:01:09,177 main DEBUG Building Plugin[name=Policies, class=org.apache.logging.log4j.core.appender.rolling.CompositeTriggeringPolicy].
2021-07-19 17:01:09,177 main DEBUG createPolicy(={OnStartupTriggeringPolicy, TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=true)})
2021-07-19 17:01:09,192 main DEBUG Building Plugin[name=appender, class=org.apache.logging.log4j.core.appender.RollingFileAppender].
2021-07-19 17:01:09,199 main DEBUG RollingFileAppender$Builder(fileName="C:\Users\nicklinn.NURRO\JCAppStore\data\logs/jcAppStore.log", filePattern="C:\Users\nicklinn.NURRO\JCAppStore\data\logs/jcAppStore_%d{yyyy-MM-dd-HH:00}.log", append="null", locking="null", Policies(CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=true)])), Strategy=null, advertise="null", advertiseUri="null", createOnDemand="null", filePermissions="null", fileOwner="null", fileGroup="null", bufferedIo="null", bufferSize="null", immediateFlush="null", ignoreExceptions="null", PatternLayout([%highlight{%-5level}] %d{DEFAULT} %c{1}.%M() - %msg%n), name="rollingFile", Configuration(jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml), Filter=null, ={})
2021-07-19 17:01:09,215 main DEBUG Returning file creation time for C:\Users\nicklinn.NURRO\JCAppStore\data\logs\jcAppStore.log
2021-07-19 17:01:09,215 main DEBUG Starting RollingFileManager C:\Users\nicklinn.NURRO\JCAppStore\data\logs/jcAppStore.log
2021-07-19 17:01:09,215 main DEBUG PluginManager 'FileConverter' found 2 plugins
2021-07-19 17:01:09,215 main DEBUG Setting prev file time to 2021-07-19T15:34:54.441-0400
2021-07-19 17:01:09,215 main DEBUG Initializing triggering policy CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=true)])
2021-07-19 17:01:09,215 main DEBUG Initializing triggering policy OnStartupTriggeringPolicy
2021-07-19 17:01:09,215 main DEBUG Initiating rollover at startup
2021-07-19 17:01:09,230 main DEBUG Formatting file name. useCurrentTime=false. currentFileTime=0, prevFileTime=1626723294441
2021-07-19 17:01:09,230 main DEBUG org.apache.logging.log4j.core.util.SystemClock does not support precise timestamps.
2021-07-19 17:01:09,230 main DEBUG Formatting file name. useCurrentTime=false. currentFileTime=0, prevFileTime=1626723294441
2021-07-19 17:01:09,230 main DEBUG OutputStream closed
2021-07-19 17:01:09,230 main DEBUG RollingFileManager executing synchronous FileRenameAction[C:\Users\nicklinn.NURRO\JCAppStore\data\logs\jcAppStore.log to C:\Users\nicklinn.NURRO\JCAppStore\data\logs\jcAppStore_2021-07-19-15:00.log, renameEmptyFiles=false]
2021-07-19 17:01:09,230 main ERROR Unable to rename file C:\Users\nicklinn.NURRO\JCAppStore\data\logs\jcAppStore.log to C:\Users\nicklinn.NURRO\JCAppStore\data\logs\jcAppStore_2021-07-19-15:00.log: java.nio.file.InvalidPathException Illegal char <:> at index 69: C:\Users\nicklinn.NURRO\JCAppStore\data\logs\jcAppStore_2021-07-19-15:00.log
2021-07-19 17:01:09,230 main DEBUG Now writing to C:\Users\nicklinn.NURRO\JCAppStore\data\logs/jcAppStore.log at 2021-07-19T17:01:09.230-0400
2021-07-19 17:01:09,230 main DEBUG Initializing triggering policy TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=true)
2021-07-19 17:01:09,230 main DEBUG Building Plugin[name=appenders, class=org.apache.logging.log4j.core.config.AppendersPlugin].
2021-07-19 17:01:09,230 main DEBUG createAppenders(={console, rollingFile})
2021-07-19 17:01:09,230 main DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2021-07-19 17:01:09,246 main DEBUG createAppenderRef(ref="console", level="null", Filter=null)
2021-07-19 17:01:09,246 main DEBUG Building Plugin[name=AppenderRef, class=org.apache.logging.log4j.core.config.AppenderRef].
2021-07-19 17:01:09,246 main DEBUG createAppenderRef(ref="rollingFile", level="null", Filter=null)
2021-07-19 17:01:09,246 main DEBUG Building Plugin[name=root, class=org.apache.logging.log4j.core.config.LoggerConfig$RootLogger].
2021-07-19 17:01:09,246 main DEBUG createLogger(additivity="false", level="ALL", includeLocation="null", ={console, rollingFile}, ={}, Configuration(jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml), Filter=null)
2021-07-19 17:01:09,246 main DEBUG Building Plugin[name=loggers, class=org.apache.logging.log4j.core.config.LoggersPlugin].
2021-07-19 17:01:09,246 main DEBUG createLoggers(={root})
2021-07-19 17:01:09,246 main DEBUG Configuration XmlConfiguration[location=jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml] initialized
2021-07-19 17:01:09,246 main DEBUG Starting configuration XmlConfiguration[location=jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml]
2021-07-19 17:01:09,246 main DEBUG Started configuration XmlConfiguration[location=jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml] OK.
2021-07-19 17:01:09,246 main DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false-1
2021-07-19 17:01:09,246 main DEBUG OutputStream closed
2021-07-19 17:01:09,246 main DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false-1, all resources released: true
2021-07-19 17:01:09,246 main DEBUG Appender DefaultConsole-1 stopped with status true
2021-07-19 17:01:09,246 main DEBUG Stopped org.apache.logging.log4j.core.config.DefaultConfiguration@48524010 OK
2021-07-19 17:01:09,299 main DEBUG Reconfiguration complete for context[name=Default] at URI jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml (org.apache.logging.log4j.core.LoggerContext@6986bbaf) with optional ClassLoader: null
2021-07-19 17:01:09,315 main DEBUG Shutdown hook enabled. Registering a new one.
2021-07-19 17:01:09,315 main DEBUG LoggerContext[name=Default, org.apache.logging.log4j.core.LoggerContext@6986bbaf] started OK.
[INFO ] 2021-07-19 17:01:09,801 SplashScreen.<init>() - Running on java 11.0.1 by Oracle Corporation in mixed mode
Exception in thread "AWT-EventQueue-0" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key The src/main/resources/ folder is missing in the application root folder.
        at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
        at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
        at cz.muni.crocs.appletstore.util.LocalizedException.getLocalizedMessage(LocalizedException.java:228)
        at java.base/java.lang.Throwable.toString(Throwable.java:485)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.io.PrintStream.println(PrintStream.java:897)
        at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
        at java.base/java.lang.Throwable.printStackTrace(Throwable.java:639)
        at cz.muni.crocs.appletstore.SplashScreen.showCrashReporter(SplashScreen.java:132)
        at cz.muni.crocs.appletstore.SplashScreen.lambda$main$2(SplashScreen.java:155)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Stopping LoggerContext[name=Default, org.apache.logging.log4j.core.LoggerContext@6986bbaf]
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Stopping LoggerContext[name=Default, org.apache.logging.log4j.core.LoggerContext@6986bbaf]...
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG OutputStream closed
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false, all resources released: true
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Appender console stopped with status true
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Shutting down RollingFileManager C:\Users\nicklinn.NURRO\JCAppStore\data\logs/jcAppStore.log
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Shutting down RollingFileManager C:\Users\nicklinn.NURRO\JCAppStore\data\logs/jcAppStore.log
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG OutputStream closed
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG All asynchronous threads have terminated
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG RollingFileManager shutdown completed with status true
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Shut down RollingFileManager C:\Users\nicklinn.NURRO\JCAppStore\data\logs/jcAppStore.log, all resources released: true
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Appender rollingFile stopped with status true
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Stopped XmlConfiguration[location=jar:file:/C:/JCAppStore/JCAppStore-1.3.exe!/log4j2.xml] OK
2021-07-19 17:01:10,820 pool-1-thread-1 DEBUG Stopped LoggerContext[name=Default, org.apache.logging.log4j.core.LoggerContext@6986bbaf] with status true
</details>

**Comment by Aiosa** [comment] 2021-07-24 11:10
This bug was fixed in the new version 2.0 that was just released.  Also, please attach such logs in `details` tags and include some human-readable information so that whoever reads the issue can understand it. 
The bug was caused by a typo (a wrong variable was being checked in a condition) due to which the store tried to show BugReporter which (again) failed due to the wrong key to a property file (already a translated string was being passed there instead of the key).

Thank you for the report.

**Closed as completed by Aiosa** 2021-07-24 11:10 UTC
Labels: bug
